version: "2.4"

services:
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

  item-app:
    # GANTI <your-docker-username> dengan username DockerHub kamu
    image: thegoodevil/item-app:v1
    ports:
      - "80:8080"
    depends_on:
      - item-db

volumes:
  app-db:
