apiVersion: v1
kind: Service
metadata:
  name: karsajobs
spec:
  selector:
    app: karsajobs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32080
  type: NodePort
