apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
spec:
  selector:
    app: karsajobs-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
